version: "3.8"

services:
  todo_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6401:6401
      - 6402:6402
    depends_on:
      - todo_rethinkdb


  todo_rethinkdb:
    image: rethinkdb:latest
    restart: always
    volumes:
      - todos_database:/data
    ports:
      - 6403:8080

volumes:
  todos_database:
